Raised when a keyword-only argument wasn't passed into a function call.

```python
def foo(first, second, *, keyword_only):
    ...

foo(1, 2, 3)
foo(first=1, second=2)

# This is okay
foo(1, 2, keyword_only=3)
```

[SOURCE](https://www.python.org/dev/peps/pep-3102/)